version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    volumes:
    - .:/var/www/html
    working_dir: /var/www/html
    networks:
    - currency-converter-inet

  nginx:
    image: nginx:latest
    ports:
    - "8000:80"
    volumes:
    - .:/var/www/html
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./var/log/nginx:/var/log/nginx
    depends_on:
    - php
    networks:
    - currency-converter-inet

networks:
  currency-converter-inet:
    driver: bridge